// AUTO-GENERATED by scripts/generate-beyblade-parts.mjs — do not edit by hand.

export interface PartOption {
  id: string;
  name: string;
  image: string;
  integratedRatchet?: boolean;
}

export const beybladeParts = {
  "bx": {
    "Bits": [
      {
        "id": "bx/bits/bitball",
        "name": "Ball",
        "image": "/beyblade-parts/bx/Bits/BitBall.png"
      },
      {
        "id": "bx/bits/bitcyclone",
        "name": "Cyclone",
        "image": "/beyblade-parts/bx/Bits/BitCyclone.png"
      },
      {
        "id": "bx/bits/bitdot",
        "name": "Dot",
        "image": "/beyblade-parts/bx/Bits/BitDot.png"
      },
      {
        "id": "bx/bits/bitelevate",
        "name": "Elevate",
        "image": "/beyblade-parts/bx/Bits/BitElevate.png"
      },
      {
        "id": "bx/bits/bitflat",
        "name": "Flat",
        "image": "/beyblade-parts/bx/Bits/BitFlat.png"
      },
      {
        "id": "bx/bits/bitfreeflat",
        "name": "Free Flat",
        "image": "/beyblade-parts/bx/Bits/BitFreeFlat.png"
      },
      {
        "id": "bx/bits/bitgearball",
        "name": "Gear Ball",
        "image": "/beyblade-parts/bx/Bits/BitGearBall.png"
      },
      {
        "id": "bx/bits/bitgearflat",
        "name": "Gear Flat",
        "image": "/beyblade-parts/bx/Bits/BitGearFlat.png"
      },
      {
        "id": "bx/bits/bitgearneedle",
        "name": "Gear Needle",
        "image": "/beyblade-parts/bx/Bits/BitGearNeedle.png"
      },
      {
        "id": "bx/bits/bitgearpoint",
        "name": "Gear Point",
        "image": "/beyblade-parts/bx/Bits/BitGearPoint.png"
      },
      {
        "id": "bx/bits/bithighneedle",
        "name": "High Needle",
        "image": "/beyblade-parts/bx/Bits/BitHighNeedle.png"
      },
      {
        "id": "bx/bits/bithightaper",
        "name": "High Taper",
        "image": "/beyblade-parts/bx/Bits/BitHighTaper.png"
      },
      {
        "id": "bx/bits/bitlowflat",
        "name": "Low Flat",
        "image": "/beyblade-parts/bx/Bits/BitLowFlat.png"
      },
      {
        "id": "bx/bits/bitmerge",
        "name": "Merge",
        "image": "/beyblade-parts/bx/Bits/BitMerge.png"
      },
      {
        "id": "bx/bits/bitneedle",
        "name": "Needle",
        "image": "/beyblade-parts/bx/Bits/BitNeedle.png"
      },
      {
        "id": "bx/bits/bitorb",
        "name": "Orb",
        "image": "/beyblade-parts/bx/Bits/BitOrb.png"
      },
      {
        "id": "bx/bits/bitpoint",
        "name": "Point",
        "image": "/beyblade-parts/bx/Bits/BitPoint.png"
      },
      {
        "id": "bx/bits/bitquake",
        "name": "Quake",
        "image": "/beyblade-parts/bx/Bits/BitQuake.png"
      },
      {
        "id": "bx/bits/bitrush",
        "name": "Rush",
        "image": "/beyblade-parts/bx/Bits/BitRush.png"
      },
      {
        "id": "bx/bits/bitspike",
        "name": "Spike",
        "image": "/beyblade-parts/bx/Bits/BitSpike.png"
      },
      {
        "id": "bx/bits/bittaper",
        "name": "Taper",
        "image": "/beyblade-parts/bx/Bits/BitTaper.png"
      },
      {
        "id": "bx/bits/bittranspoint",
        "name": "Trans Point",
        "image": "/beyblade-parts/bx/Bits/BitTransPoint.png"
      },
      {
        "id": "bx/bits/bitunite",
        "name": "Unite",
        "image": "/beyblade-parts/bx/Bits/BitUnite.png"
      }
    ],
    "Blades": [
      {
        "id": "bx/blades/bite croc",
        "name": "Bite Croc",
        "image": "/beyblade-parts/bx/Blades/Bite Croc.jpeg"
      },
      {
        "id": "bx/blades/bladeblackshell",
        "name": "Black Shell",
        "image": "/beyblade-parts/bx/Blades/BladeBlackShell.png"
      },
      {
        "id": "bx/blades/bladecobaltdragoon",
        "name": "Cobalt Dragoon",
        "image": "/beyblade-parts/bx/Blades/BladeCobaltDragoon.png"
      },
      {
        "id": "bx/blades/bladecobaltdrake",
        "name": "Cobalt Drake",
        "image": "/beyblade-parts/bx/Blades/BladeCobaltDrake.png"
      },
      {
        "id": "bx/blades/bladecrimsongaruda",
        "name": "Crimson Garuda",
        "image": "/beyblade-parts/bx/Blades/BladeCrimsonGaruda.png"
      },
      {
        "id": "bx/blades/bladedracielshield",
        "name": "Draciel Shield",
        "image": "/beyblade-parts/bx/Blades/BladeDracielShield.png"
      },
      {
        "id": "bx/blades/bladedrandagger",
        "name": "Dran Dagger",
        "image": "/beyblade-parts/bx/Blades/BladeDranDagger.png"
      },
      {
        "id": "bx/blades/bladedranstrike",
        "name": "Dran Strike",
        "image": "/beyblade-parts/bx/Blades/BladeDranStrike.png"
      },
      {
        "id": "bx/blades/bladedransword",
        "name": "Dran Sword",
        "image": "/beyblade-parts/bx/Blades/BladeDranSword.png"
      },
      {
        "id": "bx/blades/bladedranzerspiral",
        "name": "Dranzer Spiral",
        "image": "/beyblade-parts/bx/Blades/BladeDranzerSpiral.png"
      },
      {
        "id": "bx/blades/bladedrigerslash",
        "name": "Driger Slash",
        "image": "/beyblade-parts/bx/Blades/BladeDrigerSlash.png"
      },
      {
        "id": "bx/blades/bladehellschain",
        "name": "Hells Chain",
        "image": "/beyblade-parts/bx/Blades/BladeHellsChain.png"
      },
      {
        "id": "bx/blades/bladehellsscythe",
        "name": "Hells Scythe",
        "image": "/beyblade-parts/bx/Blades/BladeHellsScythe.png"
      },
      {
        "id": "bx/blades/bladeknightlance",
        "name": "Knight Lance",
        "image": "/beyblade-parts/bx/Blades/BladeKnightLance.png"
      },
      {
        "id": "bx/blades/bladeknightshield",
        "name": "Knight Shield",
        "image": "/beyblade-parts/bx/Blades/BladeKnightShield.png"
      },
      {
        "id": "bx/blades/bladeleonclaw",
        "name": "Leon Claw",
        "image": "/beyblade-parts/bx/Blades/BladeLeonClaw.png"
      },
      {
        "id": "bx/blades/bladelightningl-drago(rapid-hittype)",
        "name": "Lightning L-Drago(Rapid-Hit Type)",
        "image": "/beyblade-parts/bx/Blades/BladeLightningL-Drago(Rapid-HitType).png"
      },
      {
        "id": "bx/blades/bladelightningl-drago(uppertype)",
        "name": "Lightning L-Drago(Upper Type)",
        "image": "/beyblade-parts/bx/Blades/BladeLightningL-Drago(UpperType).png"
      },
      {
        "id": "bx/blades/bladephoenixfeather",
        "name": "Phoenix Feather",
        "image": "/beyblade-parts/bx/Blades/BladePhoenixFeather.png"
      },
      {
        "id": "bx/blades/bladephoenixwing",
        "name": "Phoenix Wing",
        "image": "/beyblade-parts/bx/Blades/BladePhoenixWing.png"
      },
      {
        "id": "bx/blades/bladerhinohorn",
        "name": "Rhino Horn",
        "image": "/beyblade-parts/bx/Blades/BladeRhinoHorn.png"
      },
      {
        "id": "bx/blades/bladerockleone",
        "name": "Rock Leone",
        "image": "/beyblade-parts/bx/Blades/BladeRockLeone.png"
      },
      {
        "id": "bx/blades/bladesamuraicalibur",
        "name": "Samurai Calibur",
        "image": "/beyblade-parts/bx/Blades/BladeSamuraiCalibur.png"
      },
      {
        "id": "bx/blades/bladesharkedge",
        "name": "Shark Edge",
        "image": "/beyblade-parts/bx/Blades/BladeSharkEdge.png"
      },
      {
        "id": "bx/blades/bladeshelterdrake",
        "name": "Shelter Drake",
        "image": "/beyblade-parts/bx/Blades/BladeShelterDrake.png"
      },
      {
        "id": "bx/blades/bladesphinxcowl",
        "name": "Sphinx Cowl",
        "image": "/beyblade-parts/bx/Blades/BladeSphinxCowl.png"
      },
      {
        "id": "bx/blades/bladestormspriggan",
        "name": "Storm Spriggan",
        "image": "/beyblade-parts/bx/Blades/BladeStormSpriggan.png"
      },
      {
        "id": "bx/blades/bladetricerapress",
        "name": "Tricera Press",
        "image": "/beyblade-parts/bx/Blades/BladeTriceraPress.png"
      },
      {
        "id": "bx/blades/bladetriceraspiky",
        "name": "Tricera Spiky",
        "image": "/beyblade-parts/bx/Blades/BladeTriceraSpiky.png"
      },
      {
        "id": "bx/blades/bladetyrannobeat",
        "name": "Tyranno Beat",
        "image": "/beyblade-parts/bx/Blades/BladeTyrannoBeat.png"
      },
      {
        "id": "bx/blades/bladeunicornsting",
        "name": "Unicorn Sting",
        "image": "/beyblade-parts/bx/Blades/BladeUnicornSting.png"
      },
      {
        "id": "bx/blades/bladevipertail",
        "name": "Viper Tail",
        "image": "/beyblade-parts/bx/Blades/BladeViperTail.png"
      },
      {
        "id": "bx/blades/bladeweisstiger",
        "name": "Weiss Tiger",
        "image": "/beyblade-parts/bx/Blades/BladeWeissTiger.png"
      },
      {
        "id": "bx/blades/bladewhalewave",
        "name": "Whale Wave",
        "image": "/beyblade-parts/bx/Blades/BladeWhaleWave.png"
      },
      {
        "id": "bx/blades/bladewizardarrow",
        "name": "Wizard Arrow",
        "image": "/beyblade-parts/bx/Blades/BladeWizardArrow.png"
      },
      {
        "id": "bx/blades/bladewyverngale",
        "name": "Wyvern Gale",
        "image": "/beyblade-parts/bx/Blades/BladeWyvernGale.png"
      },
      {
        "id": "bx/blades/bladexenoxcalibur",
        "name": "Xeno Xcalibur",
        "image": "/beyblade-parts/bx/Blades/BladeXenoXcalibur.png"
      },
      {
        "id": "bx/blades/bumblebee",
        "name": "Bumblebee",
        "image": "/beyblade-parts/bx/Blades/Bumblebee.jpeg"
      },
      {
        "id": "bx/blades/captain america",
        "name": "Captain America",
        "image": "/beyblade-parts/bx/Blades/Captain America.jpeg"
      },
      {
        "id": "bx/blades/chewbacca",
        "name": "Chewbacca",
        "image": "/beyblade-parts/bx/Blades/Chewbacca.jpeg"
      },
      {
        "id": "bx/blades/darth vader",
        "name": "Darth Vader",
        "image": "/beyblade-parts/bx/Blades/Darth Vader.jpeg"
      },
      {
        "id": "bx/blades/dragoonstorm",
        "name": "Dragoon Storm",
        "image": "/beyblade-parts/bx/Blades/DragoonStorm.jpeg"
      },
      {
        "id": "bx/blades/general grievous",
        "name": "General Grievous",
        "image": "/beyblade-parts/bx/Blades/General Grievous.jpeg"
      },
      {
        "id": "bx/blades/gill shark",
        "name": "Gill Shark",
        "image": "/beyblade-parts/bx/Blades/Gill Shark.jpeg"
      },
      {
        "id": "bx/blades/green goblin",
        "name": "Green Goblin",
        "image": "/beyblade-parts/bx/Blades/Green Goblin.jpeg"
      },
      {
        "id": "bx/blades/iron man",
        "name": "Iron Man",
        "image": "/beyblade-parts/bx/Blades/Iron Man.jpeg"
      },
      {
        "id": "bx/blades/knife shinobi",
        "name": "Knife Shinobi",
        "image": "/beyblade-parts/bx/Blades/Knife Shinobi.jpg"
      },
      {
        "id": "bx/blades/luke skywalker",
        "name": "Luke Skywalker",
        "image": "/beyblade-parts/bx/Blades/Luke Skywalker.jpeg"
      },
      {
        "id": "bx/blades/megatron",
        "name": "Megatron",
        "image": "/beyblade-parts/bx/Blades/Megatron.jpeg"
      },
      {
        "id": "bx/blades/miles morales",
        "name": "Miles Morales",
        "image": "/beyblade-parts/bx/Blades/Miles Morales.jpeg"
      },
      {
        "id": "bx/blades/moff gideon",
        "name": "Moff Gideon",
        "image": "/beyblade-parts/bx/Blades/Moff Gideon.jpeg"
      },
      {
        "id": "bx/blades/mosasaurus",
        "name": "Mosasaurus",
        "image": "/beyblade-parts/bx/Blades/Mosasaurus.png"
      },
      {
        "id": "bx/blades/obi-wan kenobi",
        "name": "Obi-Wan Kenobi",
        "image": "/beyblade-parts/bx/Blades/Obi-Wan Kenobi.jpeg"
      },
      {
        "id": "bx/blades/optimus primal",
        "name": "Optimus Primal",
        "image": "/beyblade-parts/bx/Blades/Optimus Primal.jpeg"
      },
      {
        "id": "bx/blades/optimus prime",
        "name": "Optimus Prime",
        "image": "/beyblade-parts/bx/Blades/Optimus Prime.jpeg"
      },
      {
        "id": "bx/blades/quetzalcoatlus",
        "name": "Quetzalcoatlus",
        "image": "/beyblade-parts/bx/Blades/Quetzalcoatlus.png"
      },
      {
        "id": "bx/blades/red hulk",
        "name": "Red Hulk",
        "image": "/beyblade-parts/bx/Blades/Red Hulk.jpeg"
      },
      {
        "id": "bx/blades/roar tyranno",
        "name": "Roar Tyranno",
        "image": "/beyblade-parts/bx/Blades/Roar Tyranno.jpeg"
      },
      {
        "id": "bx/blades/savage bear",
        "name": "Savage Bear",
        "image": "/beyblade-parts/bx/Blades/Savage Bear.jpg"
      },
      {
        "id": "bx/blades/shockwave",
        "name": "Shockwave",
        "image": "/beyblade-parts/bx/Blades/Shockwave.jpeg"
      },
      {
        "id": "bx/blades/spider-man",
        "name": "Spider-Man",
        "image": "/beyblade-parts/bx/Blades/Spider-Man.jpeg"
      },
      {
        "id": "bx/blades/spinosaurus",
        "name": "Spinosaurus",
        "image": "/beyblade-parts/bx/Blades/Spinosaurus.png"
      },
      {
        "id": "bx/blades/starscream",
        "name": "Starscream",
        "image": "/beyblade-parts/bx/Blades/Starscream.jpeg"
      },
      {
        "id": "bx/blades/steel samurai",
        "name": "Steel Samurai",
        "image": "/beyblade-parts/bx/Blades/Steel Samurai.jpeg"
      },
      {
        "id": "bx/blades/stormpegasis",
        "name": "Storm Pegasis",
        "image": "/beyblade-parts/bx/Blades/StormPegasis.jpeg"
      },
      {
        "id": "bx/blades/stormtrooper",
        "name": "Stormtrooper",
        "image": "/beyblade-parts/bx/Blades/Stormtrooper.jpeg"
      },
      {
        "id": "bx/blades/t. rex",
        "name": "T. Rex",
        "image": "/beyblade-parts/bx/Blades/T. Rex.png"
      },
      {
        "id": "bx/blades/tackle goat",
        "name": "Tackle Goat",
        "image": "/beyblade-parts/bx/Blades/Tackle Goat.jpeg"
      },
      {
        "id": "bx/blades/talon ptera",
        "name": "Talon Ptera",
        "image": "/beyblade-parts/bx/Blades/Talon Ptera.jpeg"
      },
      {
        "id": "bx/blades/thanos",
        "name": "Thanos",
        "image": "/beyblade-parts/bx/Blades/Thanos.jpeg"
      },
      {
        "id": "bx/blades/the mandalorian",
        "name": "The Mandalorian",
        "image": "/beyblade-parts/bx/Blades/The Mandalorian.jpeg"
      },
      {
        "id": "bx/blades/trypio",
        "name": "Trypio",
        "image": "/beyblade-parts/bx/Blades/Trypio.png"
      },
      {
        "id": "bx/blades/tusk mammoth",
        "name": "Tusk Mammoth",
        "image": "/beyblade-parts/bx/Blades/Tusk Mammoth.jpeg"
      },
      {
        "id": "bx/blades/venom",
        "name": "Venom",
        "image": "/beyblade-parts/bx/Blades/Venom.jpeg"
      },
      {
        "id": "bx/blades/victoryvalkyrie",
        "name": "Victory Valkyrie",
        "image": "/beyblade-parts/bx/Blades/VictoryValkyrie.jpeg"
      },
      {
        "id": "bx/blades/yell kong",
        "name": "Yell Kong",
        "image": "/beyblade-parts/bx/Blades/Yell Kong.jpeg"
      }
    ],
    "Ratchets": [
      {
        "id": "bx/ratchets/ratchet1-70",
        "name": "1-70",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet1-70.png"
      },
      {
        "id": "bx/ratchets/ratchet2-60",
        "name": "2-60",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet2-60.png"
      },
      {
        "id": "bx/ratchets/ratchet2-80",
        "name": "2-80",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet2-80.png"
      },
      {
        "id": "bx/ratchets/ratchet3-60",
        "name": "3-60",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet3-60.png"
      },
      {
        "id": "bx/ratchets/ratchet3-80",
        "name": "3-80",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet3-80.png"
      },
      {
        "id": "bx/ratchets/ratchet4-60",
        "name": "4-60",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet4-60.png"
      },
      {
        "id": "bx/ratchets/ratchet4-70",
        "name": "4-70",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet4-70.png"
      },
      {
        "id": "bx/ratchets/ratchet4-80",
        "name": "4-80",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet4-80.png"
      },
      {
        "id": "bx/ratchets/ratchet5-60",
        "name": "5-60",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet5-60.png"
      },
      {
        "id": "bx/ratchets/ratchet5-80",
        "name": "5-80",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet5-80.png"
      },
      {
        "id": "bx/ratchets/ratchet6-70",
        "name": "6-70",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet6-70.png"
      },
      {
        "id": "bx/ratchets/ratchet7-80",
        "name": "7-80",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet7-80.png"
      },
      {
        "id": "bx/ratchets/ratchet9-60",
        "name": "9-60",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet9-60.png"
      },
      {
        "id": "bx/ratchets/ratchet9-80",
        "name": "9-80",
        "image": "/beyblade-parts/bx/Ratchets/Ratchet9-80.png"
      },
      {
        "id": "bx/ratchets/ratchetm-85",
        "name": "M-85",
        "image": "/beyblade-parts/bx/Ratchets/RatchetM-85.png"
      }
    ]
  },
  "cx": {
    "AssistBlades": [
      {
        "id": "cx/assistblades/assistbladeassault",
        "name": "Assault",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeAssault.png"
      },
      {
        "id": "cx/assistblades/assistbladebumper",
        "name": "Bumper",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeBumper.png"
      },
      {
        "id": "cx/assistblades/assistbladecharge",
        "name": "Charge",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeCharge.png"
      },
      {
        "id": "cx/assistblades/assistbladedual (smash mode)",
        "name": "Dual (Smash Mode)",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeDual (Smash Mode).png"
      },
      {
        "id": "cx/assistblades/assistbladedual (upper mode)",
        "name": "Dual (Upper Mode)",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeDual (Upper Mode).png"
      },
      {
        "id": "cx/assistblades/assistbladeerase",
        "name": "Erase",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeErase.png"
      },
      {
        "id": "cx/assistblades/assistbladefree",
        "name": "Free",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeFree.png"
      },
      {
        "id": "cx/assistblades/assistbladeheavy",
        "name": "Heavy",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeHeavy.png"
      },
      {
        "id": "cx/assistblades/assistbladejaggy",
        "name": "Jaggy",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeJaggy.png"
      },
      {
        "id": "cx/assistblades/assistbladeknuckle",
        "name": "Knuckle",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeKnuckle.png"
      },
      {
        "id": "cx/assistblades/assistblademassive",
        "name": "Massive",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeMassive.png"
      },
      {
        "id": "cx/assistblades/assistbladeodd",
        "name": "Odd",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeOdd.png"
      },
      {
        "id": "cx/assistblades/assistbladeround",
        "name": "Round",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeRound.png"
      },
      {
        "id": "cx/assistblades/assistbladeslash",
        "name": "Slash",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeSlash.png"
      },
      {
        "id": "cx/assistblades/assistbladeturn",
        "name": "Turn",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeTurn.png"
      },
      {
        "id": "cx/assistblades/assistbladevertical",
        "name": "Vertical",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeVertical.png"
      },
      {
        "id": "cx/assistblades/assistbladewheel",
        "name": "Wheel",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeWheel.png"
      },
      {
        "id": "cx/assistblades/assistbladezillion",
        "name": "Zillion",
        "image": "/beyblade-parts/cx/AssistBlades/AssistBladeZillion.png"
      }
    ],
    "Bits": [
      {
        "id": "cx/bits/bitgearrush",
        "name": "Gear Rush",
        "image": "/beyblade-parts/cx/Bits/BitGearRush.png"
      },
      {
        "id": "cx/bits/bitgearunite",
        "name": "Gear Unite",
        "image": "/beyblade-parts/cx/Bits/BitGearUnite.png"
      },
      {
        "id": "cx/bits/bitignition",
        "name": "Ignition",
        "image": "/beyblade-parts/cx/Bits/BitIgnition.png"
      },
      {
        "id": "cx/bits/bitkick",
        "name": "Kick",
        "image": "/beyblade-parts/cx/Bits/BitKick.png"
      },
      {
        "id": "cx/bits/bitloworb",
        "name": "Low Orb",
        "image": "/beyblade-parts/cx/Bits/BitLowOrb.png"
      },
      {
        "id": "cx/bits/bitnarrow",
        "name": "Narrow",
        "image": "/beyblade-parts/cx/Bits/BitNarrow.png"
      },
      {
        "id": "cx/bits/bittranskick",
        "name": "Trans Kick",
        "image": "/beyblade-parts/cx/Bits/BitTransKick.png"
      },
      {
        "id": "cx/bits/bitvortex",
        "name": "Vortex",
        "image": "/beyblade-parts/cx/Bits/BitVortex.png"
      },
      {
        "id": "cx/bits/bitwallball",
        "name": "Wall Ball",
        "image": "/beyblade-parts/cx/Bits/BitWallBall.png"
      },
      {
        "id": "cx/bits/bitwallwedge",
        "name": "Wall Wedge",
        "image": "/beyblade-parts/cx/Bits/BitWallWedge.png"
      },
      {
        "id": "cx/bits/bitwedge",
        "name": "Wedge",
        "image": "/beyblade-parts/cx/Bits/BitWedge.png"
      },
      {
        "id": "cx/bits/bityielding",
        "name": "Yielding",
        "image": "/beyblade-parts/cx/Bits/BitYielding.png"
      }
    ],
    "LockChips": [
      {
        "id": "cx/lockchips/lockchipbahamut",
        "name": "Bahamut",
        "image": "/beyblade-parts/cx/LockChips/LockChipBahamut.png"
      },
      {
        "id": "cx/lockchips/lockchipbrachio",
        "name": "Brachio",
        "image": "/beyblade-parts/cx/LockChips/LockChipBrachio.png"
      },
      {
        "id": "cx/lockchips/lockchipcerberus",
        "name": "Cerberus",
        "image": "/beyblade-parts/cx/LockChips/LockChipCerberus.png"
      },
      {
        "id": "cx/lockchips/lockchipdran",
        "name": "Dran",
        "image": "/beyblade-parts/cx/LockChips/LockChipDran.png"
      },
      {
        "id": "cx/lockchips/lockchipemperor",
        "name": "Emperor",
        "image": "/beyblade-parts/cx/LockChips/LockChipEmperor.png"
      },
      {
        "id": "cx/lockchips/lockchipevaunit-01",
        "name": "Eva Unit-01",
        "image": "/beyblade-parts/cx/LockChips/LockChipEvaUnit-01.png"
      },
      {
        "id": "cx/lockchips/lockchipfox",
        "name": "Fox",
        "image": "/beyblade-parts/cx/LockChips/LockChipFox.png"
      },
      {
        "id": "cx/lockchips/lockchiphells",
        "name": "Hells",
        "image": "/beyblade-parts/cx/LockChips/LockChipHells.png"
      },
      {
        "id": "cx/lockchips/lockchiphornet",
        "name": "Hornet",
        "image": "/beyblade-parts/cx/LockChips/LockChipHornet.png"
      },
      {
        "id": "cx/lockchips/lockchipknight",
        "name": "Knight",
        "image": "/beyblade-parts/cx/LockChips/LockChipKnight.png"
      },
      {
        "id": "cx/lockchips/lockchipkraken",
        "name": "Kraken",
        "image": "/beyblade-parts/cx/LockChips/LockChipKraken.png"
      },
      {
        "id": "cx/lockchips/lockchipleon",
        "name": "Leon",
        "image": "/beyblade-parts/cx/LockChips/LockChipLeon.png"
      },
      {
        "id": "cx/lockchips/lockchippegasus",
        "name": "Pegasus",
        "image": "/beyblade-parts/cx/LockChips/LockChipPegasus.png"
      },
      {
        "id": "cx/lockchips/lockchipperseus",
        "name": "Perseus",
        "image": "/beyblade-parts/cx/LockChips/LockChipPerseus.png"
      },
      {
        "id": "cx/lockchips/lockchipphoenix",
        "name": "Phoenix",
        "image": "/beyblade-parts/cx/LockChips/LockChipPhoenix.png"
      },
      {
        "id": "cx/lockchips/lockchipragna",
        "name": "Ragna",
        "image": "/beyblade-parts/cx/LockChips/LockChipRagna.png"
      },
      {
        "id": "cx/lockchips/lockchiprhino",
        "name": "Rhino",
        "image": "/beyblade-parts/cx/LockChips/LockChipRhino.png"
      },
      {
        "id": "cx/lockchips/lockchipsol",
        "name": "Sol",
        "image": "/beyblade-parts/cx/LockChips/LockChipSol.png"
      },
      {
        "id": "cx/lockchips/lockchipstag",
        "name": "Stag",
        "image": "/beyblade-parts/cx/LockChips/LockChipStag.png"
      },
      {
        "id": "cx/lockchips/lockchipunicorn",
        "name": "Unicorn",
        "image": "/beyblade-parts/cx/LockChips/LockChipUnicorn.png"
      },
      {
        "id": "cx/lockchips/lockchipvalkyrie",
        "name": "Valkyrie",
        "image": "/beyblade-parts/cx/LockChips/LockChipValkyrie.png"
      },
      {
        "id": "cx/lockchips/lockchipwhale",
        "name": "Whale",
        "image": "/beyblade-parts/cx/LockChips/LockChipWhale.png"
      },
      {
        "id": "cx/lockchips/lockchipwizard",
        "name": "Wizard",
        "image": "/beyblade-parts/cx/LockChips/LockChipWizard.png"
      },
      {
        "id": "cx/lockchips/lockchipwolf",
        "name": "Wolf",
        "image": "/beyblade-parts/cx/LockChips/LockChipWolf.png"
      }
    ],
    "MainBlades": [
      {
        "id": "cx/mainblades/mainbladearc",
        "name": "Arc",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeArc.png"
      },
      {
        "id": "cx/mainblades/mainbladeblast",
        "name": "Blast",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeBlast.png"
      },
      {
        "id": "cx/mainblades/mainbladebrave",
        "name": "Brave",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeBrave.png"
      },
      {
        "id": "cx/mainblades/mainbladebrush",
        "name": "Brush",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeBrush.png"
      },
      {
        "id": "cx/mainblades/mainbladedark",
        "name": "Dark",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeDark.png"
      },
      {
        "id": "cx/mainblades/mainbladeeclipse (smash mode)",
        "name": "Eclipse (Smash Mode)",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeEclipse (Smash Mode).png"
      },
      {
        "id": "cx/mainblades/mainbladeeclipse (upper mode)",
        "name": "Eclipse (Upper Mode)",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeEclipse (Upper Mode).png"
      },
      {
        "id": "cx/mainblades/mainbladefang",
        "name": "Fang",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeFang.png"
      },
      {
        "id": "cx/mainblades/mainbladeflame",
        "name": "Flame",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeFlame.png"
      },
      {
        "id": "cx/mainblades/mainbladeflare",
        "name": "Flare",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeFlare.png"
      },
      {
        "id": "cx/mainblades/mainbladefort",
        "name": "Fort",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeFort.png"
      },
      {
        "id": "cx/mainblades/mainbladehunt",
        "name": "Hunt",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeHunt.png"
      },
      {
        "id": "cx/mainblades/mainblademight",
        "name": "Might",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeMight.png"
      },
      {
        "id": "cx/mainblades/mainbladereaper",
        "name": "Reaper",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeReaper.png"
      },
      {
        "id": "cx/mainblades/mainbladevolt",
        "name": "Volt",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeVolt.png"
      },
      {
        "id": "cx/mainblades/mainbladewriggle",
        "name": "Wriggle",
        "image": "/beyblade-parts/cx/MainBlades/MainBladeWriggle.png"
      }
    ],
    "MetalBlades": [
      {
        "id": "cx/metalblades/metalbladeblitz",
        "name": "Blitz",
        "image": "/beyblade-parts/cx/MetalBlades/MetalBladeBlitz.png"
      },
      {
        "id": "cx/metalblades/metalbladedelta",
        "name": "Delta",
        "image": "/beyblade-parts/cx/MetalBlades/MetalBladeDelta.png"
      },
      {
        "id": "cx/metalblades/metalbladefortress",
        "name": "Fortress",
        "image": "/beyblade-parts/cx/MetalBlades/MetalBladeFortress.png"
      },
      {
        "id": "cx/metalblades/metalbladerage",
        "name": "Rage",
        "image": "/beyblade-parts/cx/MetalBlades/MetalBladeRage.png"
      },
      {
        "id": "cx/metalblades/metalbladewhip",
        "name": "Whip",
        "image": "/beyblade-parts/cx/MetalBlades/MetalBladeWhip.png"
      }
    ],
    "OverBlades": [
      {
        "id": "cx/overblades/overbladebreak",
        "name": "Break",
        "image": "/beyblade-parts/cx/OverBlades/OverBladeBreak.png"
      },
      {
        "id": "cx/overblades/overbladeflow",
        "name": "Flow",
        "image": "/beyblade-parts/cx/OverBlades/OverBladeFlow.png"
      },
      {
        "id": "cx/overblades/overbladeguard",
        "name": "Guard",
        "image": "/beyblade-parts/cx/OverBlades/OverBladeGuard.png"
      },
      {
        "id": "cx/overblades/overbladeouter",
        "name": "Outer",
        "image": "/beyblade-parts/cx/OverBlades/OverBladeOuter.png"
      },
      {
        "id": "cx/overblades/overbladepeak",
        "name": "Peak",
        "image": "/beyblade-parts/cx/OverBlades/OverBladePeak.png"
      }
    ],
    "Ratchets": [
      {
        "id": "cx/ratchets/ratchet0-60",
        "name": "0-60",
        "image": "/beyblade-parts/cx/Ratchets/Ratchet0-60.png"
      },
      {
        "id": "cx/ratchets/ratchet1-50",
        "name": "1-50",
        "image": "/beyblade-parts/cx/Ratchets/Ratchet1-50.png"
      },
      {
        "id": "cx/ratchets/ratchet4-55",
        "name": "4-55",
        "image": "/beyblade-parts/cx/Ratchets/Ratchet4-55.png"
      },
      {
        "id": "cx/ratchets/ratchet6-60",
        "name": "6-60",
        "image": "/beyblade-parts/cx/Ratchets/Ratchet6-60.png"
      },
      {
        "id": "cx/ratchets/ratchet6-80",
        "name": "6-80",
        "image": "/beyblade-parts/cx/Ratchets/Ratchet6-80.png"
      },
      {
        "id": "cx/ratchets/ratchet8-70",
        "name": "8-70",
        "image": "/beyblade-parts/cx/Ratchets/Ratchet8-70.png"
      }
    ]
  },
  "ux": {
    "Bits": [
      {
        "id": "ux/bits/bitaccel",
        "name": "Accel",
        "image": "/beyblade-parts/ux/Bits/BitAccel.png"
      },
      {
        "id": "ux/bits/bitboundspike",
        "name": "Bound Spike",
        "image": "/beyblade-parts/ux/Bits/BitBoundSpike.png"
      },
      {
        "id": "ux/bits/bitdiskball",
        "name": "Disk Ball",
        "image": "/beyblade-parts/ux/Bits/BitDiskBall.png"
      },
      {
        "id": "ux/bits/bitfreeball",
        "name": "Free Ball",
        "image": "/beyblade-parts/ux/Bits/BitFreeBall.png"
      },
      {
        "id": "ux/bits/bitglide",
        "name": "Glide",
        "image": "/beyblade-parts/ux/Bits/BitGlide.png"
      },
      {
        "id": "ux/bits/bithexa",
        "name": "Hexa",
        "image": "/beyblade-parts/ux/Bits/BitHexa.png"
      },
      {
        "id": "ux/bits/bitjolt",
        "name": "Jolt",
        "image": "/beyblade-parts/ux/Bits/BitJolt.png"
      },
      {
        "id": "ux/bits/bitlevel",
        "name": "Level",
        "image": "/beyblade-parts/ux/Bits/BitLevel.png"
      },
      {
        "id": "ux/bits/bitlowrush",
        "name": "Low Rush",
        "image": "/beyblade-parts/ux/Bits/BitLowRush.png"
      },
      {
        "id": "ux/bits/bitmetalneedle",
        "name": "Metal Needle",
        "image": "/beyblade-parts/ux/Bits/BitMetalNeedle.png"
      },
      {
        "id": "ux/bits/bitrubberaccel",
        "name": "Rubber Accel",
        "image": "/beyblade-parts/ux/Bits/BitRubberAccel.png"
      },
      {
        "id": "ux/bits/bitunderflat",
        "name": "Under Flat",
        "image": "/beyblade-parts/ux/Bits/BitUnderFlat.png"
      },
      {
        "id": "ux/bits/bitunderneedle",
        "name": "Under Needle",
        "image": "/beyblade-parts/ux/Bits/BitUnderNeedle.png"
      },
      {
        "id": "ux/bits/bitzap",
        "name": "Zap",
        "image": "/beyblade-parts/ux/Bits/BitZap.png"
      }
    ],
    "Blades": [
      {
        "id": "ux/blades/bladeaeropegasus",
        "name": "Aero Pegasus",
        "image": "/beyblade-parts/ux/Blades/BladeAeroPegasus.png"
      },
      {
        "id": "ux/blades/bladeclockmirage",
        "name": "Clock Mirage",
        "image": "/beyblade-parts/ux/Blades/BladeClockMirage.png"
      },
      {
        "id": "ux/blades/bladedranbuster",
        "name": "Dran Buster",
        "image": "/beyblade-parts/ux/Blades/BladeDranBuster.png"
      },
      {
        "id": "ux/blades/bladeghostcircle",
        "name": "Ghost Circle",
        "image": "/beyblade-parts/ux/Blades/BladeGhostCircle.png"
      },
      {
        "id": "ux/blades/bladegolemrock",
        "name": "Golem Rock",
        "image": "/beyblade-parts/ux/Blades/BladeGolemRock.png"
      },
      {
        "id": "ux/blades/bladehackviking",
        "name": "Hack Viking",
        "image": "/beyblade-parts/ux/Blades/BladeHackViking.png"
      },
      {
        "id": "ux/blades/bladehellshammer",
        "name": "Hells Hammer",
        "image": "/beyblade-parts/ux/Blades/BladeHellsHammer.png"
      },
      {
        "id": "ux/blades/bladeimpactdrake",
        "name": "Impact Drake",
        "image": "/beyblade-parts/ux/Blades/BladeImpactDrake.png"
      },
      {
        "id": "ux/blades/bladeknightmail",
        "name": "Knight Mail",
        "image": "/beyblade-parts/ux/Blades/BladeKnightMail.png"
      },
      {
        "id": "ux/blades/bladeleoncrest",
        "name": "Leon Crest",
        "image": "/beyblade-parts/ux/Blades/BladeLeonCrest.png"
      },
      {
        "id": "ux/blades/blademeteordragoon",
        "name": "Meteor Dragoon",
        "image": "/beyblade-parts/ux/Blades/BladeMeteorDragoon.png"
      },
      {
        "id": "ux/blades/blademummycurse",
        "name": "Mummy Curse",
        "image": "/beyblade-parts/ux/Blades/BladeMummyCurse.png"
      },
      {
        "id": "ux/blades/bladeorochicluster",
        "name": "Orochi Cluster",
        "image": "/beyblade-parts/ux/Blades/BladeOrochiCluster.png"
      },
      {
        "id": "ux/blades/bladephoenixrudder",
        "name": "Phoenix Rudder",
        "image": "/beyblade-parts/ux/Blades/BladePhoenixRudder.png"
      },
      {
        "id": "ux/blades/bladesamuraisaber",
        "name": "Samurai Saber",
        "image": "/beyblade-parts/ux/Blades/BladeSamuraiSaber.png"
      },
      {
        "id": "ux/blades/bladescorpiospear",
        "name": "Scorpio Spear",
        "image": "/beyblade-parts/ux/Blades/BladeScorpioSpear.png"
      },
      {
        "id": "ux/blades/bladesharkscale",
        "name": "Shark Scale",
        "image": "/beyblade-parts/ux/Blades/BladeSharkScale.png"
      },
      {
        "id": "ux/blades/bladeshinobishadow",
        "name": "Shinobi Shadow",
        "image": "/beyblade-parts/ux/Blades/BladeShinobiShadow.png"
      },
      {
        "id": "ux/blades/bladesilverwolf",
        "name": "Silver Wolf",
        "image": "/beyblade-parts/ux/Blades/BladeSilverWolf.png"
      },
      {
        "id": "ux/blades/bladewizardrod",
        "name": "Wizard Rod",
        "image": "/beyblade-parts/ux/Blades/BladeWizardRod.png"
      },
      {
        "id": "ux/blades/hover wyvern",
        "name": "Hover Wyvern",
        "image": "/beyblade-parts/ux/Blades/Hover Wyvern.jpeg"
      },
      {
        "id": "ux/blades/ratchetbladebulletgriffon",
        "name": "Bullet Griffon",
        "image": "/beyblade-parts/ux/Blades/RatchetBladeBulletGriffon.png",
        "integratedRatchet": true
      },
      {
        "id": "ux/blades/ratchetbladecuttershinobi",
        "name": "Cutter Shinobi",
        "image": "/beyblade-parts/ux/Blades/RatchetBladeCutterShinobi.png",
        "integratedRatchet": true
      },
      {
        "id": "ux/blades/ratchetbladegloryvalkyrie",
        "name": "Glory Valkyrie",
        "image": "/beyblade-parts/ux/Blades/RatchetBladeGloryValkyrie.png",
        "integratedRatchet": true
      },
      {
        "id": "ux/blades/ratchetbladerampartaegis",
        "name": "Rampart Aegis",
        "image": "/beyblade-parts/ux/Blades/RatchetBladeRampartAegis.png",
        "integratedRatchet": true
      },
      {
        "id": "ux/blades/ratchetbladevalorbison",
        "name": "Valor Bison",
        "image": "/beyblade-parts/ux/Blades/RatchetBladeValorBison.png",
        "integratedRatchet": true
      },
      {
        "id": "ux/blades/stun medusa",
        "name": "Stun Medusa",
        "image": "/beyblade-parts/ux/Blades/Stun Medusa.jpeg"
      }
    ],
    "Ratchets": [
      {
        "id": "ux/ratchets/ratchet0-70",
        "name": "0-70",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet0-70.png"
      },
      {
        "id": "ux/ratchets/ratchet0-80",
        "name": "0-80",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet0-80.png"
      },
      {
        "id": "ux/ratchets/ratchet1-60",
        "name": "1-60",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet1-60.png"
      },
      {
        "id": "ux/ratchets/ratchet1-80",
        "name": "1-80",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet1-80.png"
      },
      {
        "id": "ux/ratchets/ratchet2-70",
        "name": "2-70",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet2-70.png"
      },
      {
        "id": "ux/ratchets/ratchet3-70",
        "name": "3-70",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet3-70.png"
      },
      {
        "id": "ux/ratchets/ratchet3-85",
        "name": "3-85",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet3-85.png"
      },
      {
        "id": "ux/ratchets/ratchet4-50",
        "name": "4-50",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet4-50.png"
      },
      {
        "id": "ux/ratchets/ratchet5-70",
        "name": "5-70",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet5-70.png"
      },
      {
        "id": "ux/ratchets/ratchet7-55",
        "name": "7-55",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet7-55.png"
      },
      {
        "id": "ux/ratchets/ratchet7-60",
        "name": "7-60",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet7-60.png"
      },
      {
        "id": "ux/ratchets/ratchet7-70",
        "name": "7-70",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet7-70.png"
      },
      {
        "id": "ux/ratchets/ratchet9-65",
        "name": "9-65",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet9-65.png"
      },
      {
        "id": "ux/ratchets/ratchet9-70",
        "name": "9-70",
        "image": "/beyblade-parts/ux/Ratchets/Ratchet9-70.png"
      }
    ]
  }
} as const satisfies Record<string, Record<string, PartOption[]>>;
